# Generated by Django 2.1.2 on 2018-10-19 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloudips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudipsname', models.CharField(max_length=10, verbose_name='服务器运营商')),
                ('describe', models.CharField(max_length=10, verbose_name='描述')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '服务器运营商',
                'verbose_name_plural': '服务器运营商',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='服务器名称')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='服务器IP地址')),
                ('sshuser', models.CharField(max_length=20, verbose_name='服务器登陆用户')),
                ('sshpassword', models.CharField(max_length=20, verbose_name='服务器登陆密码')),
                ('websitepath', models.CharField(max_length=200, verbose_name='网站存放位置')),
                ('sshport', models.SmallIntegerField(default=22, verbose_name='服务器登陆端口')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_maintenance', models.BooleanField(default=0, verbose_name='是否维护')),
                ('deploy_times', models.IntegerField(default=1, verbose_name='部署队列和计划任务次数')),
                ('cloudips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Cloudips', verbose_name='服务器运营商')),
            ],
            options={
                'verbose_name': '用户设备信息',
                'verbose_name_plural': '用户设备信息',
            },
        ),
        migrations.CreateModel(
            name='Envirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envname', models.CharField(max_length=20, verbose_name='服务器运行环境')),
                ('describe', models.CharField(max_length=20, verbose_name='描述')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '运行环境',
                'verbose_name_plural': '运行环境',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('path', models.CharField(max_length=100, verbose_name='任务路径')),
                ('describe', models.CharField(max_length=30, verbose_name='描述')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='envirment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Envirment', verbose_name='运行环境'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客户用户名'),
        ),
    ]
