# Generated by Django 2.1.2 on 2018-10-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deploy_times',
            field=models.IntegerField(default=1, verbose_name='部署队列和计划任务次数'),
        ),
    ]
