# Generated by Django 2.1.2 on 2018-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20181017_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='customer_name',
            field=models.CharField(max_length=20, null=True, verbose_name='客户用户名'),
        ),
        migrations.AddField(
            model_name='device',
            name='others',
            field=models.TextField(null=True, verbose_name='其他内容'),
        ),
    ]
