# Generated by Django 2.1.2 on 2018-11-14 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20181107_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated_at_deploy',
            field=models.DateField(default=datetime.datetime.now, verbose_name='部署队列任务时间'),
        ),
    ]
