# Generated by Django 2.1.2 on 2018-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_device_updated_at_deploy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='updated_at_deploy',
            field=models.TextField(null=True, verbose_name='部署记录'),
        ),
    ]
