# Generated by Django 2.1.2 on 2018-11-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20181114_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='updated_at_deploy',
            new_name='deploy_desc',
        ),
    ]
