# Generated by Django 2.1.2 on 2018-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20181115_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploy_record',
            options={'verbose_name': '部署记录', 'verbose_name_plural': '部署记录'},
        ),
        migrations.AddField(
            model_name='device',
            name='maintenance_duration',
            field=models.CharField(max_length=20, null=True, verbose_name='维护期限'),
        ),
    ]
