# Generated by Django 2.1.2 on 2018-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20181116_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='others',
            field=models.TextField(blank=True, null=True, verbose_name='其他内容'),
        ),
    ]
