# Generated by Django 2.1.2 on 2018-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_auto_20181116_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='envirment',
            name='phpbin',
            field=models.CharField(max_length=100, null=True, verbose_name='PHP环境路径'),
        ),
    ]
