# Generated by Django 2.1.4 on 2019-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_envirment_phpbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sshport',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='服务器登陆端口'),
        ),
    ]
