# Generated by Django 2.1.7 on 2019-03-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_auto_20190327_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deploy_times',
            field=models.IntegerField(default=0, verbose_name='部署队列和计划任务次数'),
        ),
    ]
