# Generated by Django 2.2.2 on 2019-06-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_auto_20190329_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy_record',
            name='jobname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='device.Jobs', verbose_name='任务名称'),
        ),
    ]
