# Generated by Django 2.2.2 on 2019-06-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_deploy_record_jobname'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deploy_shop_times',
            field=models.SmallIntegerField(default=0, verbose_name='部署商城次数'),
        ),
        migrations.AddField(
            model_name='device',
            name='paid',
            field=models.BooleanField(default=0, verbose_name='商城收费客户'),
        ),
    ]
