# Generated by Django 2.2.2 on 2019-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_auto_20190628_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deploy_shop_times',
        ),
        migrations.AddField(
            model_name='device',
            name='deploy_frameworkshop_times',
            field=models.SmallIntegerField(default=0, verbose_name='部署微擎与商城次数'),
        ),
        migrations.AddField(
            model_name='device',
            name='deploy_weiqingshop_times',
            field=models.SmallIntegerField(default=0, verbose_name='部署框架与商城次数'),
        ),
    ]
