# Generated by Django 2.2.3 on 2019-11-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_auto_20190628_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='服务器名称'),
        ),
    ]