# Generated by Django 2.2.9 on 2020-02-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0023_auto_20191126_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy_record',
            name='hostname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_record', to='device.Device', verbose_name='服务器名称'),
        ),
        migrations.AlterField(
            model_name='deploy_record',
            name='jobname',
            field=models.CharField(max_length=16, null=True, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='deploy_record',
            name='operator',
            field=models.CharField(max_length=20, null=True, verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ipaddress',
            field=models.GenericIPAddressField(db_index=True, verbose_name='服务器IP地址'),
        ),
    ]
