# Generated by Django 2.2.9 on 2020-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0024_auto_20200210_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy_record',
            name='jobname',
            field=models.CharField(max_length=32, null=True, verbose_name='任务名称'),
        ),
    ]
