# Generated by Django 2.2.9 on 2020-02-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0026_deploy_record_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ftppassword',
            field=models.CharField(max_length=32, null=True, verbose_name='ftp密码'),
        ),
        migrations.AddField(
            model_name='device',
            name='ftpuser',
            field=models.CharField(default='www', max_length=32, verbose_name='ftp用户名'),
        ),
        migrations.AddField(
            model_name='device',
            name='mysqlpassword',
            field=models.CharField(max_length=32, null=True, verbose_name='mysql密码'),
        ),
        migrations.AddField(
            model_name='device',
            name='mysqluser',
            field=models.CharField(default='root', max_length=32, verbose_name='mysql用户名'),
        ),
    ]
