# Generated by Django 2.2.9 on 2020-03-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0027_auto_20200224_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mysqladdress',
            field=models.CharField(default='127.0.0.1', max_length=32, verbose_name='mysql连接地址'),
        ),
    ]
