# Generated by Django 2.2.9 on 2020-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0028_device_mysqladdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mysqladdress',
            field=models.CharField(default='127.0.0.1', max_length=64, verbose_name='mysql连接地址'),
        ),
    ]
