# Generated by Django 2.2.9 on 2020-05-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0029_auto_20200309_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='envirment',
            name='vhost_path',
            field=models.CharField(max_length=100, null=True, verbose_name='网站虚拟目录路径'),
        ),
    ]
