# Generated by Django 2.2.9 on 2020-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0030_envirment_vhost_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='shop_version',
            field=models.BooleanField(default=0, verbose_name='商城版本'),
        ),
    ]
