# Generated by Django 2.2.9 on 2020-05-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0031_device_shop_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sshpassword', models.CharField(max_length=600, verbose_name='服务器登陆密码')),
                ('ftppassword', models.CharField(max_length=600, null=True, verbose_name='ftp密码')),
                ('mysqlpassword', models.CharField(max_length=600, null=True, verbose_name='mysql密码')),
                ('ipaddress', models.ForeignKey(db_column='server_ip', on_delete=django.db.models.deletion.CASCADE, related_name='PASSWORD', to='device.Device')),
            ],
            options={
                'verbose_name': '密码表',
                'verbose_name_plural': '密码表',
                'permissions': (('select_table', '查看密码表'), ('change_table', '修改密码表'), ('decode_password', '解密加密密码')),
                'default_permissions': (),
            },
        ),
    ]
