# Generated by Django 2.2.15 on 2020-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0032_password_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mongodbaddress',
            field=models.CharField(default='127.0.0.1', max_length=64, verbose_name='mongodb连接地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='mongodbuser',
            field=models.CharField(default='root', max_length=32, verbose_name='mongodb用户名'),
        ),
        migrations.AddField(
            model_name='password_record',
            name='mongodbpassword',
            field=models.CharField(max_length=600, null=True, verbose_name='mongodb密码'),
        ),
    ]
