# Generated by Django 2.2.16 on 2020-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0033_auto_20200825_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='describe',
            field=models.CharField(max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=50, verbose_name='任务名称'),
        ),
    ]
