# Generated by Django 2.2.17 on 2021-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0034_auto_20201009_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy_record',
            name='result',
            field=models.TextField(null=True, verbose_name='执行任务结果'),
        ),
    ]
