# Generated by Django 2.2.15 on 2020-08-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=50, verbose_name='域名')),
                ('is_blacklist', models.BooleanField(default=0, verbose_name='是否黑名单')),
            ],
            options={
                'verbose_name': '域名详情',
                'verbose_name_plural': '域名详情',
            },
        ),
    ]
