# Generated by Django 2.2.15 on 2020-08-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaindetail',
            name='domain',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='域名'),
        ),
    ]
